spring:
  application:
    name: Customer-Service
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: 27017
      database: movieapp

server:
  port: 8082
  error:
    include-message: always


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/